# permissions for end users to view custompromexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompromexporter-viewer-role
rules:
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters/status
  verbs:
  - get
