# permissions for end users to edit custompromexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custompromexporter-editor-role
rules:
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters/status
  verbs:
  - get
