---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters/finalizers
  verbs:
  - update
- apiGroups:
  - apps.iscale.cc
  resources:
  - custompromexporters/status
  verbs:
  - get
  - patch
  - update
